### ISSUE TITLE
Improve tag functionality

### ISSUE THREAD

**Issue by LVerhulst4321** [lostcarpark/conclar#101]
Add the ability to identify tags that should not be part of a filter dropdown, but still show in the panel description.
Also add the ability to identify tags that should be in a filter dropdown, but not be part of the panel description.

**Comment by lostcarpark** [comment]
I have added HIDE properties to the config, to allow specified drop-downs to be hidden, though tags will still be shown on program items.

**Comment by lostcarpark** [comment]
This is resolved by PR #102.

**Comment by LVerhulst4321** [comment]
Cool! I'll check it out.
