### ISSUE TITLE
Show timezone abbreviation setting

### ISSUE THREAD

**Issue by LVerhulst4321** [lostcarpark/conclar#114]
I've had a request to show the timezone abbreviations on the program page next to the start times. 
I was wondering if we could add this as a setting option.

![image](https://user-images.githubusercontent.com/25570607/184245623-a594f7ed-3316-406d-9ed8-e2757409d9cc.png)

**Comment by lostcarpark** [comment]
What would you like the display to show? It would be easy to set a label in config to show after the convention timezone... e.g. 1:00 PM CDT. 

I'll have to check if we can get the user's local timezone code.

**Comment by lostcarpark** [comment]
PR #115 resolves by adding timezone short name after time.
It can be configured on settings page.

![image](https://user-images.githubusercontent.com/17686819/184473849-3e909c3a-9d9f-471c-a7c6-4504e7354dd3.png)
