### ISSUE TITLE
production option: minify bundle.js

### ISSUE THREAD

**Issue by offbyone** [lostcarpark/conclar#122]
While we definitely want the full code in development, in production we should minify `bundle.js` which is currently 9.38MB over the wire. That's cacheable, but it's expensive.

(related, we should make sure we have good cache control headers on it so that our updates go out properly)

**Comment by lostcarpark** [comment]
It looks like the `npm run build` step isn't getting run when moving the application into the docker container. That includes a minification step, and should end up with the bundled JavaScript being called something like `main.9364da6e.js`. On my test site that's ending up a little under 1MB. That should help improve the startup time a bit.

**Comment by LVerhulst4321** [comment]
This was an issue with the way I was deploying the docker container that I set up for Chicon 8.
