### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mcdemarco** [lostcarpark/conclar#16]
I made some css changes in my fork that you may or may not be interested in: 
https://github.com/mcdemarco/conclar/commits/style

- Turn checkboxes into buttons with css
- Make thumbnails circular with some shadow
- Fix layout esp. responsive wrapping of program items
- Style nav as buttons 
- Improve filter spacing; for better spacing restructure HTML
- Set fonts

I can submit a pull request for the lot if that's easier.

**Comment by lostcarpark** [comment]
That's a nice bit of styling. I would definitely love to incorporate it.
However, on my display, it's making the checkbox to the left of each programme item disappear, preventing you from selecting items to display on "My Schedule".

**Comment by mcdemarco** [comment]
Oops.  I got ambitious with the new checkboxes (there was only the thumbnails one in the version I started styling) and overshot.  It's fixed now.

**Comment by mcdemarco** [comment]
Pull request #17.

**Comment by lostcarpark** [comment]
Great work!

The body font was not rendering using font smoothing in Firefox for Linux (except for ligature characters, which looked really odd). I took Calibri off the font list and it looks fine now. It could possibly be put back if the order was changed.

I also added "break-inside: avoid" to the participants to stop the thumbnail and the name splitting across columns.

One more thing. I've added a "12 hour" checkbox. There's a minor issue that the new option is left aligned and the "show local time" is right aligned. Do I need to put options in a Div so they can be grouped easily?

Finally, I've added a table of contents to the CSS file to make it easier to find things.

**Comment by mcdemarco** [comment]
> Great work!

Thanks!

> The body font was not rendering using font smoothing in Firefox for Linux (except for ligature characters, which looked really odd). I took Calibri off the font list and it looks fine now. It could possibly be put back if the order was changed.

If you can tell which font is being used in FF after your change, just put Calibri after it, or move it to the beginning of the list.  (Firebug should highlight which font is actually in effect in the computed styles.)

> One more thing. I've added a "12 hour" checkbox. There's a minor issue that the new option is left aligned and the "show local time" is right aligned. Do I need to put options in a Div so they can be grouped easily?

It never hurts to wrap related stuff in a div.

**Comment by mcdemarco** [comment]
Closed by/with PR #17.

**Comment by lostcarpark** [comment]
I have moved most of the colours into CSS variables. This should make it easier for people to recolour easily.
