### ISSUE TITLE
No default page

### ISSUE THREAD

**Issue by mcdemarco** [lostcarpark/conclar#21]
Routing doesn't default to a page; if you hit the root you get navigation, the footer, and nothing in between, which is a bit confusing.  I think KonOpas defaults to the program(me).

**Comment by lostcarpark** [comment]
I've been looking at the React-Router documentation, but I haven't figured out how to do this yet.

**Comment by mcdemarco** [comment]
I think this was fixed for me with the correct htaccess file for Apache.  The readme should probably mention that one is already set up for build/deploy in the public directory.

**Comment by lostcarpark** [comment]
Ah good to hear.
I think there's an issue that if you manually pick an invalid path, it will display the header and footer and nothing between.
I need to add a fake 404 page at some point.
I agree I need to mention the default `.htaccess` file. Is it getting copied into the build folder for you? It didn't seem to be for me.

**Comment by mcdemarco** [comment]
Yes, it got copied.  My OS hides it and my sftp GUI doesn't see it so it's a bit of a hassle to actually deploy.  I should switch to rsync...

**Comment by lostcarpark** [comment]
Ah, I was mistaken, it is in fact in my build directory (my webserver runs Nginx, so I don't actually need it). I'll update the Readme accordingly.

**Comment by lostcarpark** [comment]
This now displays an error message when visiting an unknown URL, so I think can be closed.
