### ISSUE TITLE
Refresh for schedule changes?

### ISSUE THREAD

**Issue by mcdemarco** [lostcarpark/conclar#24]
Is there a way to refresh the schedule when it changes on the server?  KonOpas does this as part of the caching mechanism (using cron jobs to check for schedule changes, download them to the server, and update the cache manifest file).  A caching mechanism would also be great, but I think refresh is more urgent.

**Comment by lostcarpark** [comment]
This is something I'm planning to work on shortly. My intention is to have it periodically attempt to refetch the data, and if successful replace the stored data. Ultimately I hope to be able to highlight programme items that have changed.

**Comment by lostcarpark** [comment]
Resolved by pull request #67.
