### ISSUE TITLE
Person pages need to scroll to top

### ISSUE THREAD

**Issue by mcdemarco** [lostcarpark/conclar#25]
@olszowka noticed that when you're scrolled down in the people list and click on a person, that person's page loads scrolled down as well.  If their schedule is long enough (and the phone is small enough), you don't see their bio at all, just the schedule.

**Comment by lostcarpark** [comment]
Very good point. I've added a ScrollToTop component to do this.
A downside is it seems to sometimes scroll to top when going back to the previous page.

**Comment by lostcarpark** [comment]
Pull Request #28 merged to resolve.

**Comment by mcdemarco** [comment]
Seems fixed!
